### ISSUE TITLE
review

### ISSUE THREAD

**Issue by KojiHonjoh** [yabu397/inst_browser_app#4]
- lib/features/bookmark/presentation/widgets/bookmark_form_dialog.dart
端末サイズが小さい場合にキーボード表示でオーバーフローで操作できないので、スクロールなどで操作できるようにしてください。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/domain/providers/bookmark_provider.dart#L16

>respository

typoです

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/screens/bookmark_screen.dart#L9

stateを利用していないので、statefullWidgetにする必要がないのでstatelessWidgetにしましょう。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/widgets/browser_button_bar.dart#L15

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/widgets/bookmark_form_bdy.dart#L14

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/widgets/bookmark_form_bdy.dart#L15

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/widgets/bookmark_form_buttons.dart#L18

[build内でreadの使用は禁止されています](https://riverpod.dev/docs/concepts/reading#using-refread-to-obtain-the-state-of-a-provider)。watchを使用してください。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/screens/browser_screen.dart#L15
SafeAreaはScaffoldのbodyで使用してください。表示が崩れています。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/widgets/browser_button.dart#L5

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/widgets/browser_button.dart#L7
- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/widgets/browser_button.dart#L8
オプショナルにする理由が無いのでrequiredにしましょう。
onPressed関数はvoidを明示するか、VoidCallBackを利用しましょう。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/widgets/bookmark_list.dart#L97
context.pushを使用しましょう。ブックマーク画面に戻る際に画面の再生成が必要になります。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/widgets/browser_button_bar.dart#L27
context.popを使用しましょう。画面を入れ替えている状態になっているので、前の画面に戻る処理にしてあげるのが自然です。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/shared/widgets/cst_snack_bar.dart#L4
textをオプショナルにする理由がないのでrequiredにしましょう。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/shared/widgets/cst_snack_bar.dart#L6
ExpandedをRowやColumn内のみしか使用できません。
何故使用しているのか分かりませんが、使用しないようにしましょう。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/widgets/bookmark_list.dart#L89
webViewでJavaScriptが使用できないのでsetjavascriptmodeで使用できるようにしましょう。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/providers/browser_state_provider.dart#L6
- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/providers/bookmark_state_provider.dart#L7
[stateNotiferは非推奨](https://riverpod.dev/ja/docs/migration/from_state_notifier)なので(Async)Notifierを使うように修正してください。

**Comment by yabu397** [comment]
@KojiHonjoh 
ご指摘いただいた内容Developにマージしました。
確認お願い致します。

**Comment by KojiHonjoh** [comment]
@yabu397 

https://github.com/yabu397/inst_browser_app/blob/develop/lib/features/bookmark/presentation/providers/bookmark_state_provider.dart#L19

初期化時にreadしないでください。このアプリでは無いケースですが、bookmarkRepositoryProviderに変更があった場合に検知できません。
またメンバとして持つ必要がないです。
`await bookmarkRepository`
としている箇所は全て
`await ref.read(bookmarkRepositoryProvider)`
で対応できます（refを参照できます）。
この場合は呼び出し時にのみ利用するので、watchではなくreadで構いません。

**Comment by yabu397** [comment]
@KojiHonjoh 
ご指摘いただいた内容Developにマージしました。
確認お願い致します。

**Comment by KojiHonjoh** [comment]
@yabu397 
追加で以下の改善をお願いします。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/browser/presentation/screens/browser_screen.dart#L28
- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/widgets/bookmark_list.dart#L108
高さをデバイス依存で算出していますが、小さいデバイスの場合表示が崩れるので、表示が崩れない固定値を与えるか、閾値を設けてください。

- https://github.com/yabu397/inst_browser_app/blob/97814012571a4e71214283913f0786db4a4408b9/lib/features/bookmark/presentation/widgets/bookmark_list.dart#L79-L129

Cardを使用せずにContainerを使用するように修正してみてください。
条件は下記です。
・枠線を表示すること
・InkWellのRipple Efectを表示すること

**Comment by yabu397** [comment]
@KojiHonjoh 
承知いたしました。
対応させていただきます。

**Comment by yabu397** [comment]
@KojiHonjoh
Developにマージしました。
確認お願い致します。
